<?php
require_once __DIR__ . '/contratoConstantes.php';

// Contrato Outsourcing Equipamento Status
// const CONTRATO_OUTSOURCING_EQUIPAMENTO_ATIVO = 'a';
// const CONTRATO_OUTSOURCING_EQUIPAMENTO_INATIVO = 'i';

// const CONTRATO_OUTSOURCING_EQUIPAMENTO_STATUS_LIST = [
//     CONTRATO_OUTSOURCING_EQUIPAMENTO_ATIVO,
//     CONTRATO_OUTSOURCING_EQUIPAMENTO_INATIVO
// ];

const EQP_STATUS_ATIVO = 'a';
const EQP_STATUS_INATIVO = 'i';
const EQP_STATUS_TODOS = null;

const EQP_CATEGORIA_DESKTOP_WORKSTATION = 1;
const EQP_CATEGORIA_NOTEBOOK = 2;
const EQP_CATEGORIA_SERVIDOR_FISICO = 3;
const EQP_CATEGORIA_SERVIDOR_VIRTUAL = 4;
const EQP_CATEGORIA_SERVIDOR_NUVEM = 25;
const EQP_CATEGORIA_STORAGE = 5;
const EQP_CATEGORIA_NOBREAK = 6;
const EQP_CATEGORIA_OUTROS = 7;
const EQP_CATEGORIA_TODOS = 8;
const EQP_CATEGORIA_APS = 9;

