<?php

// Contrato Status
const CONTRATO_STATUS_INATIVO = 1;
const CONTRATO_STATUS_ATIVO = 2;

const CONTRATO_TIPO_ATIVO = 'a';
const CONTRATO_TIPO_INATIVO = 'i';

// Contrato Outsourcing Equipamento Status
const CONTRATO_OUTSOURCING_EQUIPAMENTO_ATIVO = 'a';
const CONTRATO_OUTSOURCING_EQUIPAMENTO_INATIVO = 'i';

const CONTRATO_OUTSOURCING_EQUIPAMENTO_STATUS_LIST = [
    CONTRATO_OUTSOURCING_EQUIPAMENTO_ATIVO,
    CONTRATO_OUTSOURCING_EQUIPAMENTO_INATIVO
];

// Contrato Tipos Ids
const CONTRATO_HELPDESK_ID = 1;
const CONTRATO_HOSPEDAGEM_ID = 2;
const CONTRATO_BHCLOUD_ERP_ID = 3;
const CONTRATO_DOMINIO_ID = 4;
const CONTRATO_BACKUP_ID = 5;
const CONTRATO_SUPORTE_PRODUTO_ID = 6;

const CONTRATOS_OUTSOURCING_ID_LIST = [
    CONTRATO_HELPDESK_ID,
];
